import fastRandom from 'fast-random'

export const createSeededRandom = fastRandom

const MASK = 0xffffffff // 32bit
const MAX = 2 ** 36 // 36bit

/**
 * Generate stateless random number from two seeds.
 * * Generated by ChatGPT and hand-written.
 */
export function papRandom(baseSeed: number, subSeed: number = 0): number {
  // 入力値の制約を32ビットにする
  baseSeed &= MASK
  subSeed &= MASK

  // 32ビットの乱数生成ロジック（独自のロジックを使用しています）
  const upper = (0x6c078965 * (baseSeed ^ (baseSeed >>> 30)) + subSeed) & MASK
  const lower = (0x6c078965 * (subSeed ^ (subSeed >>> 30)) + baseSeed) & MASK

  // 36ビットの乱数を作成
  // upperの上位4ビットを取得し、それを32ビット左シフトしてlowerと組み合わせる
  const result = ((upper & 0xf0000000) >>> 28) * 2 ** 32 + (lower & 0x7fffffff)

  return result
}

export function papRandomFloat(baseSeed: number, indexSeed: number = 0) {
  return papRandom(baseSeed, indexSeed) / MAX
}
