'use client'

import { ThemeProvider, createGlobalStyle } from 'styled-components'
import { light, dark } from '@charcoal-ui/theme'
import {
  TokenInjector,
  prefersColorScheme,
  themeSelector
} from '@charcoal-ui/styled'
import reset from 'styled-reset'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js'
// }

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyle />

      <body>
        <ThemeProvider theme={light}>
          <TokenInjector
            theme={{
              ':root': light,
              [themeSelector('light')]: light,
              [themeSelector('dark')]: dark,
              [prefersColorScheme('dark')]: dark
            }}
            background="background1"
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

const GlobalStyle = createGlobalStyle`
  ${reset}

  html, body {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
  }
`
