name: Yarn install and build
description: Install dependencies and build the project

inputs:
  node-version:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          .yarn/cache
          node_modules/
        key: ${{ runner.os }}-node${{ inputs.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-node${{ inputs.node-version }}-

    - name: Install native libs
      shell: bash
      run: |
        sudo apt-get update -y

        # for node-canvas
        sudo apt-get install xserver-xorg-dev libxi-dev libxext-dev

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: yarn install
