#!/usr/bin/env deno run --allow-read --allow-write

import { encodeBase64 } from 'jsr:@std/encoding/base64'
import { expandGlob } from 'jsr:@std/fs'
import { basename, dirname, extname, join } from 'jsr:@std/path'

/**
 * Denoスクリプト: PNG画像をbase64エンコードしてindex.tsを生成
 * 使用方法: deno run --allow-read --allow-write _update.deno.ts
 */

async function main() {
  const currentDir = dirname(new URL(import.meta.url).pathname)

  // 同階層の.pngファイルを検索
  const pngFiles: string[] = (
    await Array.fromAsync(expandGlob('*.png', { root: currentDir }))
  )
    .filter((file) => file.isFile)
    .map((file) => basename(file.path))

  // 各PNGファイルをbase64エンコード
  const encodedImages: Record<string, string> = {}

  for (const pngFile of pngFiles) {
    const filePath = join(currentDir, pngFile)
    const fileData = await Deno.readFile(filePath)
    const base64Data = encodeBase64(fileData)

    // ファイル名から拡張子を除いてキャメルケースに変換
    const baseName = basename(pngFile, extname(pngFile))
    const variableName = toCamelCase(baseName)

    encodedImages[variableName] = base64Data
  }

  // index.tsファイルを生成
  const indexContent = generateIndexContent(encodedImages)
  const indexPath = join(currentDir, 'index.ts')

  await Deno.writeTextFile(indexPath, indexContent)
}

/**
 * ケバブケースやスネークケースをキャメルケースに変換
 */
function toCamelCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[-_](.)/g, (_, char) => char.toUpperCase())
    .replace(/^(.)/, (char) => char.toLowerCase())
}

/**
 * index.tsファイルの内容を生成
 */
function generateIndexContent(encodedImages: Record<string, string>): string {
  const exports = Object.keys(encodedImages)
    .map((varName) => `  ${varName}`)
    .join(',\n')

  const definitions = Object.entries(encodedImages)
    .map(([varName, base64Data]) => {
      return `export const ${varName} = '${base64Data}';`
    })
    .join('\n\n')

  return `// Generated by _update.deno.ts - Do not edit manually
// Run: deno run --allow-read --allow-write _update.deno.ts

/**
 * Base64 encoded PNG brush textures
 *
 * Texture Format Specification:
 * - Alpha map: 0 (black/dark) = transparent, 1 (bright/white) = opaque
 * - Color composition: Bright areas are multiplied with brush color
 * - Luminance-based alpha: Uses (R+G+B)/3 as alpha value with threshold
 * - Expected usage: Fragment shader applies brush color to non-transparent areas
 */

${definitions}

// Export all brush textures
export const brushTextures = {
${exports}
};
`
}

// スクリプト実行
if (import.meta.main) {
  main()
}
