#!/usr/bin/env deno run --allow-read --allow-write

import { join, dirname, basename, extname } from 'jsr:@std/path'
import { expandGlob } from 'jsr:@std/fs'
import { encodeBase64 } from 'jsr:@std/encoding/base64'

/**
 * Denoスクリプト: PNG画像をbase64エンコードしてindex.tsを生成
 * 使用方法: deno run --allow-read --allow-write _update.deno.ts
 */

async function main() {
  const currentDir = dirname(new URL(import.meta.url).pathname)

  // 同階層の.pngファイルを検索
  const pngFiles: string[] = (
    await Array.fromAsync(expandGlob('*.png', { root: currentDir }))
  )
    .filter((file) => file.isFile)
    .map((file) => basename(file.path))

  // 各PNGファイルをbase64エンコード
  const encodedImages: Record<string, string> = {}

  for (const pngFile of pngFiles) {
    const filePath = join(currentDir, pngFile)
    const fileData = await Deno.readFile(filePath)
    const base64Data = encodeBase64(fileData)

    // ファイル名から拡張子を除いてキャメルケースに変換
    const baseName = basename(pngFile, extname(pngFile))
    const variableName = toCamelCase(baseName)

    encodedImages[variableName] = base64Data
  }

  // index.tsファイルを生成
  const indexContent = generateIndexContent(encodedImages)
  const indexPath = join(currentDir, 'index.ts')

  await Deno.writeTextFile(indexPath, indexContent)
}

/**
 * ケバブケースやスネークケースをキャメルケースに変換
 */
function toCamelCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[-_](.)/g, (_, char) => char.toUpperCase())
    .replace(/^(.)/, (char) => char.toLowerCase())
}

/**
 * index.tsファイルの内容を生成
 */
function generateIndexContent(encodedImages: Record<string, string>): string {
  const exports = Object.keys(encodedImages)
    .map((varName) => `  ${varName}`)
    .join(',\n')

  const definitions = Object.entries(encodedImages)
    .map(([varName, base64Data]) => {
      return `/**
 * Base64 encoded ${varName} brush texture
 * Usage: const img = new Image(); img.src = 'data:image/png;base64,' + ${varName};
 */
export const ${varName} = '${base64Data}';`
    })
    .join('\n\n')

  return `// Generated by _update.deno.ts - Do not edit manually
// Run: deno run --allow-read --allow-write _update.deno.ts

${definitions}

// Export all brush textures
export const brushTextures = {
${exports}
};

// Utility function to create Image objects from base64 data
export function createImageFromBase64(base64Data: string): HTMLImageElement {
  const img = new Image();
  img.src = 'data:image/png;base64,' + base64Data;
  return img;
}

// Utility function to create Blob from base64 data
export function createBlobFromBase64(base64Data: string): Blob {
  const binaryString = atob(base64Data);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return new Blob([bytes], { type: 'image/png' });
}
`
}

// スクリプト実行
if (import.meta.main) {
  main()
}
