'use client'

import type {} from '@/lib/cssprop'
import { ThemeProvider, createGlobalStyle } from 'styled-components'
import { ServerStyleSheet, StyleSheetManager } from 'styled-components'
import { light, dark } from '@charcoal-ui/theme'
import {
  TokenInjector,
  prefersColorScheme,
  themeSelector,
} from '@charcoal-ui/styled'
import reset from 'styled-reset'
import React, { useState } from 'react'
import { useServerInsertedHTML } from 'next/navigation'
import '@radix-ui/themes/styles.css'
import { Theme } from '@radix-ui/themes'
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry'
import { ModalProvider } from '@/components/Dialog'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js'
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyle />

          <Theme style={{ width: '100%', height: '100%' }} accentColor="lime">
            <ThemeProvider theme={light}>
              <TokenInjector
                theme={{
                  ':root': light,
                  [themeSelector('light')]: light,
                  [themeSelector('dark')]: dark,
                  [prefersColorScheme('dark')]: dark,
                }}
                background="background1"
              />
              <ModalProvider>{children}</ModalProvider>
            </ThemeProvider>
          </Theme>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

const GlobalStyle = createGlobalStyle`
  ${reset}

  *, *::before, *::after {
    box-sizing: border-box;
  }

  html, body {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    touch-action: manipulation;
    overflow: hidden;

    *:not(input, textarea){
      user-select: none;
    }
  }

  :root {
    --pap-sufrace-dropshadow: rgba(0,0,0,.2);
    --pap-sufrace-dropshadow-size: 24px;
  }
`
