'use client'

import type {} from '@/lib/cssprop'
import { createGlobalStyle } from 'styled-components'
import reset from 'styled-reset'
import React from 'react'
import { Theme } from '@radix-ui/themes'
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry'
import { ModalProvider } from '@/components/Dialog'
import '@radix-ui/themes/styles.css'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js'
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <Theme
          asChild
          style={{ width: '100%', height: '100%' }}
          accentColor="lime">
          <body>
            <GlobalStyle />
            <ModalProvider>{children}</ModalProvider>
          </body>
        </Theme>
      </StyledComponentsRegistry>
    </html>
  )
}

const GlobalStyle = createGlobalStyle`
  ${reset}

  *, *::before, *::after {
    box-sizing: border-box;
  }

  html, body {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    touch-action: manipulation;
    overflow: hidden;

    *:not(input, textarea){
      user-select: none;
    }
  }

  :root {
    --pap-sufrace-dropshadow: rgba(0,0,0,.2);
    --pap-sufrace-dropshadow-size: 24px;
  }
`
