name: Building
description: Build all packages

runs:
  using: composite
  steps:
    - name: Build (shared-lib)
      shell: bash
      working-directory: ./pkgs/shared-lib
      run: |
        pwd
        yarn build

    - name: Build (chat)
      shell: bash
      working-directory: ./pkgs/chat
      run: |
        pwd
        yarn build

    - name: Build (core)
      shell: bash
      working-directory: ./pkgs/core
      run: |
        pwd
        yarn build

    - name: Build (editor)
      shell: bash
      working-directory: ./pkgs/editor
      run: |
        pwd
        yarn build

    - name: Build (chat)
      shell: bash
      working-directory: ./pkgs/editor
      run: |
        pwd
        yarn build

    - name: Build (web)
      shell: bash
      working-directory: ./pkgs/web2
      run: |
        pwd
        yarn build
