name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/setup.yml
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - uses: ./actions/building.yml
