name: Deoloy

on: [push]

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        env:
          BUILD_TARGET_ENV: 'production'
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/building

      - name: Deploying to Vercel
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./pkgs/web2
