name: Testing

on: [push]

jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/setup.yml
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}

      - name: Testing @paplico/core-new
        continue-on-error: true
        run: |
          cd pkgs/core
          # yarn prepublishOnly
          yarn test

      - name: Testing @paplico/web2
        continue-on-error: true
        run: |
          cd pkgs/web2
          yarn test
